const films = [{
        id: "1",
        title: "The Conjuring",
        poster: "https://m.media-amazon.com/images/I/81yAfVk+7UL._AC_SY606_.jpg",
        decription: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
        rate: 5,
    },
    {
        id: "2",
        title: "The Grudge",
        poster: "https://aws-cf.imdoc.fr/prod/photos/8/6/1/11904861/29176577/big-29176577abb.jpg?v=2",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 5,
    },
    {
        id: "3",
        title: "The Ring",
        poster: "https://m.media-amazon.com/images/I/41CGtdWTDvL._AC_.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 1,
    },
    {
        id: "4",
        title: "The Shawshank Redemption",
        poster: "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
    },
    {
        id: "5",
        title: "The Godfather",
        poster: "https://ih1.redbubble.net/image.1275475865.6561/pp,504x498-pad,600x600,f8f8f8.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
    },
    {
        id: "6",
        title: "The Godfather: Part II",
        poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0hYUlSTUgCxfY-8ACz_E3CQWDKShEYEvGFw&usqp=CAU",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
    },
    {
        id: "7",
        title: "The Dark Knight",
        poster: "https://m.media-amazon.com/images/I/51CbCQNMyiL._AC_.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 2,
    },
    {
        id: "8",
        title: "12 Angry Men",
        poster: "https://m.media-amazon.com/images/I/81zZhjymV7L._AC_SL1500_.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 4,
    },
    {
        id: "9",
        title: "Drifting Home",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/iNf1wC8cK6e8zgNyuMUqWFT7Din.jpg",
        decription: "Paranormal investigators Ed and Lorraine Warren work ",
        rate: 2,
    },
    {
        id: "10",
        title: "SPY x FAMILY",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/3r4LYFuXrg3G8fepysr4xSLWnQL.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
    },
    {
        id: "11",
        title: "Peaky Blinders",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 1,
    },
    {
        id: "12",
        title: "Transporter 3",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/gucv9gRRnVFDyqeIS1KC7irnX0b.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
    },
    {
        id: "13",
        title: "Pokémon",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/rOuGm07PxBhEsK9TaGPRQVJQm1X.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
    },
    {
        id: "14",
        title: "The School for Good and Evil",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/6oZeEu1GDILdwezmZ5e2xWISf1C.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 3,
    },
    {
        id: "15",
        title: "The Forbidden Kingdom",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/mkrwLBAFHwLnQF8qdhCH0VOQqff.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 2,
    },
    {
        id: "16",
        title: "The Three Musketeers",
        poster: "https://www.themoviedb.org/t/p/w220_and_h330_face/w2LbQ8FvZiQpWvZyHljaOeiNknK.jpg",
        decription: "The Ring is a 2002 American supernatural horror film",
        rate: 4,
    },
];

export default films;